sudo: required
dist: trusty
language: python
python:
  - "3.5"
before_install: 
  - set -ev
  - sudo apt-get update
install:
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install tqdm
script: python ngramModelTrainer.py