sudo: required
dist: trusty
language: python
python:
  - "2.7"
before_install: 
  - set -ev
  - sudo apt-get update
install:
  - pip install --only-binary=numpy,scipy numpy scipy
script: python ngramModelTrainer.py